name: sudoku
description: "Sudoku - Neon Theme"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# --- App launcher icon config ---
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # <-- unified path
  adaptive_icon_background: "#000000" # optional (Android)
  adaptive_icon_foreground: "assets/logo.png"

# --- Native splash config ---
flutter_native_splash:
  color: "#0b0b0f"
  image: assets/logo.png # <-- unified path
  android: true
  ios: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png # <-- make sure this file exists
